name: balena-etcher-electron
version: 1.5.89
summary: balenaEtcher
description: 'Flash OS images to SD cards and USB drives, safely and easily.'
architectures:
  - build-on: amd64
 # - build-on: i386
base: core20
grade: stable
confinement: classic


parts:
  ecther-files:
    plugin: dump
    source: 
      - on amd64: https://github.com/balena-io/etcher/releases/download/v$SNAPCRAFT_PROJECT_VERSION/balena-etcher-electron_$SNAPCRAFT_PROJECT_VERSION_amd64.deb
     # - on i386: https://github.com/balena-io/etcher/releases/download/v$SNAPCRAFT_PROJECT_VERSION/balena-etcher-electron_$SNAPCRAFT_PROJECT_VERSION_i386.deb
    source-type: deb
    override-build: |
       snapcraftctl build
       mv $SNAPCRAFT_PART_INSTALL/opt/balenaEtcher $SNAPCRAFT_PART_INSTALL/app
    stage:
      - '-opt'
      - '-usr'
      - '-app/chrome-sandbox'
      - '-LICENSES.chromium.html'
      
  additional-packages:
    plugin: nil
    stage-packages:
      - libnode-dev
  
  #
  # ALL PARTS BELOW are generated by electron-builder
  #
  launch-scripts:
    plugin: dump
    source: scripts
  gnome-platform-empty-dirs:
    plugin: nil
    override-build: |
      mkdir -p "$SNAPCRAFT_PART_INSTALL/data-dir/themes" mkdir -p "$SNAPCRAFT_PART_INSTALL/data-dir/icons" mkdir -p "$SNAPCRAFT_PART_INSTALL/data-dir/sounds" mkdir $SNAPCRAFT_PART_INSTALL/gnome-platform
  
  # Stage-packages are takes from the dependancies list
  # of the .deb file.
  app:
    plugin: nil
    stage:
      - '-usr/lib/python*'
      - '-usr/bin/python*'
      - '-var/lib/ucf'
      - '-usr/include'
      - '-usr/lib/X11'
      - '-usr/share'
      - '-usr/sbin'
      - '-usr/bin'
      - '-usr/lib/*/libicudata.*'
      - '-usr/lib/*/libicui18n.*'
      - '-usr/lib/*/libgtk-*'
      - '-usr/lib/*/libgdk-*'
      - '-usr/lib/*/glib-*'
      - '-usr/lib/*/gtk-*'
      - '-usr/lib/*/gdk-*'
      - '-usr/lib/*/krb5'
      - '-usr/lib/systemd'
      - '-usr/lib/glib-networking'
      - '-usr/lib/dconf'
      - '-usr/lib/*/avahi'
      - '-usr/lib/*/gio'
      - '-usr/lib/*/libatk*'
      - '-usr/lib/*/libatspi*'
      - '-usr/lib/*/libavahi*'
      - '-usr/lib/*/libcairo*'
      - '-usr/lib/*/libcolordprivate*'
      - '-usr/lib/*/libcolord*'
      - '-usr/lib/*/libcroco*'
      - '-usr/lib/*/libcups*'
      - '-usr/lib/*/libdatrie*'
      - '-usr/lib/*/libdconf*'
      - '-usr/lib/*/libepoxy*'
      - '-usr/lib/*/libexpatw*'
      - '-usr/lib/*/libffi*'
      - '-usr/lib/*/libfontconfig*'
      - '-usr/lib/*/libfreetype*'
      - '-usr/lib/*/libgdk_pixbuf*'
      - '-usr/lib/*/libgdk_pixbuf_xlib*'
      - '-usr/lib/*/libgio*'
      - '-usr/lib/*/libglib*'
      - '-usr/lib/*/libgmodule*'
      - '-usr/lib/*/libgmp*'
      - '-usr/lib/*/libgnutls*'
      - '-usr/lib/*/libgobject*'
      - '-usr/lib/*/libgraphite2*'
      - '-usr/lib/*/libgssapi_krb5*'
      - '-usr/lib/*/libgthread*'
      - '-usr/lib/*/libharfbuzz*'
      - '-usr/lib/*/libhogweed*'
      - '-usr/lib/*/libicuio*'
      - '-usr/lib/*/libicutest*'
      - '-usr/lib/*/libicutu*'
      - '-usr/lib/*/libicuuc*'
      - '-usr/lib/*/libidn2*'
      - '-usr/lib/*/libjbig*'
      - '-usr/lib/*/libjpeg*'
      - '-usr/lib/*/libjson*'
      - '-usr/lib/*/libk5crypto*'
      - '-usr/lib/*/libkrb5*'
      - '-usr/lib/*/libkrb5support*'
      - '-usr/lib/*/liblcms2*'
      - '-usr/lib/*/libnettle*'
      - '-usr/lib/*/libp11*'
      - '-usr/lib/*/libpango*'
      - '-usr/lib/*/libpangocairo*'
      - '-usr/lib/*/libpangoft2*'
      - '-usr/lib/*/libpixman*'
      - '-usr/lib/*/libpng16*'
      - '-usr/lib/*/libproxy*'
      - '-usr/lib/*/librest*'
      - '-usr/lib/*/librsvg*'
      - '-usr/lib/*/libsecret*'
      - '-usr/lib/*/libsoup*'
      - '-usr/lib/*/libsqlite3*'
      - '-usr/lib/*/libtasn1*'
      - '-usr/lib/*/libthai*'
      - '-usr/lib/*/libtiff*'
      - '-usr/lib/*/libunistring*'
      - '-usr/lib/*/libwayland*'
      - '-usr/lib/*/libX11*'
      - '-usr/lib/*/libXau*'
      - '-usr/lib/*/libxcb*'
      - '-usr/lib/*/libXcomposite*'
      - '-usr/lib/*/libXcursor*'
      - '-usr/lib/*/libXdamage*'
      - '-usr/lib/*/libXdmcp*'
      - '-usr/lib/*/libXext*'
      - '-usr/lib/*/libXfixes*'
      - '-usr/lib/*/libXinerama*'
      - '-usr/lib/*/libXi*'
      - '-usr/lib/*/libxkbcommon*'
      - '-usr/lib/*/libxml2*'
      - '-usr/lib/*/libXrandr*'
      - '-usr/lib/*/libXrender*'
    stage-packages:
      - gconf2
      - gconf-service
      - libappindicator1
      - libasound2
      - libatk1.0-0
      - libc6
      - libcairo2
      - libcups2
      - libdbus-1-3
      - libexpat1
      - libfontconfig1
      - libfreetype6
      - libgcc1
      - libgconf-2-4
      - libgdk-pixbuf2.0-0
      - libglib2.0-0
      - libgtk2.0-0
      - liblzma5
      - libnotify4
      - libnspr4
      - libnss3
      - libpango1.0-0
      - libpango-1.0-0
      - libstdc++6
      - libx11-6
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxext6
      - libxfixes3
      - libxi6
      - libxrandr2
      - libxrender1
      - libxss1
      - libxtst6
apps:
  balena-etcher-electron:
    command: command.sh
    adapter: none
icon: snap/gui/icon.png
